language: objective-c
osx_image: xcode7
branches:
  only:
    - master
before_install:
  - gem install xcpretty
script:
- set -o pipefail
- xcodebuild -project Example/SnappingStepperExample.xcodeproj -scheme Tests -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPad 2" ONLY_ACTIVE_ARCH=NO test | xcpretty -c
